#!/usr/bin/env python

# Copyright 2015 Jonas Stenling <jonas@stenling.se>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

DOCUMENTATION = '''
---

module: iosxe_get_facts
short_description: Return facts for router
description:
    - Will return interfaces and vrfs present in router as facts.
author: Jonas Stenling 
requirements:
    - IOS XE with Netconf enabled
    - pyskate

options:
    host:
        description:
            - IP Address or hostname (resolvable by Ansible control host)
              of the target Netconf IOS-XE enabled router.
        required: true
        default: null
        choices: []
        aliases: []
    username:
        description:
            - Username used to login to the router.
        required: true
        default: null
        choices: []
        aliases: []
    password:
        description:
            - Password used to login to the router.
        required: true
        default: null
        choices: []
        aliases: []
'''

EXAMPLES = '''

# Get facts from router.
- iosxe_get_facts:
    host: {{ inventory_hostname }}
    username: {{ username }}
    password: {{ password }}
'''
try:
    import socket
    from pyskate.iosxe_netconf import IOSXEDevice
except ImportError as e:
    print '*' * 30
    print e
    print '*' * 30


def parse_config(config):
    '''Returns dict of interfaces and vrfs in the router by parsing
    *config*.'''

    interfaces = []
    vrfs = []

    (STATE_GLOBAL,
     STATE_VRF,
     STATE_INTERFACE) = range(3)

    state = STATE_GLOBAL

    for line in config:
        if state == STATE_GLOBAL:
            if line.startswith("vrf definition"):
                vrfs.append(line.split()[2]) # append vrf name only
                state = STATE_VRF
            elif line.startswith("interface"):
                interfaces.append(line.split()[1]) # append interface name only
                state = STATE_INTERFACE
        if state == STATE_VRF:
            if line.startswith("!"):
                state = STATE_GLOBAL
        if state == STATE_INTERFACE:
            if line.startswith("!"):
                state = STATE_GLOBAL
    return {'interfaces': interfaces, 'vrfs': vrfs}

def main():

    module = AnsibleModule(
        argument_spec=dict(
            host=dict(required=True),
            username=dict(type='str'),
            password=dict(type='str'),
        ),
        supports_check_mode=True
    )

    username = module.params['username']
    password = module.params['password']
    host = socket.gethostbyname(module.params['host'])

    device = IOSXEDevice(host, username, password)

    try:
        device.connect()
    except:
        module.fail_json(msg="Failed to connect to {0}".format(host))

    running_config = device.get_config()

    facts = parse_config(running_config)

    device.disconnect()

    module.exit_json(ansible_facts=facts)

from ansible.module_utils.basic import *
main()
