#!/usr/bin/env python

# Copyright 2015 Jonas Stenling <jonas@stenling.se>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

DOCUMENTATION = '''
---

module: iosxe_save_config
short_description: Save running configuration to startup configuration.
description:
    - Will copy running configuration to startup configuration in router.
author: Jonas Stenling 
requirements:
    - IOS XE with Netconf enabled
    - pyskate

options:
    host:
        description:
            - IP Address or hostname (resolvable by Ansible control host)
              of the target Netconf IOS-XE enabled router.
        required: true
        default: null
        choices: []
        aliases: []
    username:
        description:
            - Username used to login to the router.
        required: true
        default: null
        choices: []
        aliases: []
    password:
        description:
            - Password used to login to the router.
        required: true
        default: null
        choices: []
        aliases: []
'''

EXAMPLES = '''

# Execute show command in router
- iosxe_save_config
    host: {{ inventory_hostname }}
    username: {{ username }}
    password: {{ password }}
'''
try:
    import socket
    from pyskate.iosxe_netconf import IOSXEDevice
except ImportError as e:
    print '*' * 30
    print e
    print '*' * 30

def main():

    module = AnsibleModule(
        argument_spec=dict(
            host=dict(required=True),
            username=dict(type='str'),
            password=dict(type='str'),
        ),
        supports_check_mode=False
    )

    username = module.params['username']
    password = module.params['password']
    host = socket.gethostbyname(module.params['host'])

    device = IOSXEDevice(host, username, password)

    try:
        device.connect()
    except:
        module.fail_json(msg="Failed to connect to {0}".format(host))

    try:
        if device.save_config():
            results = {}
            results['changed'] = True
        else:
            results = {}
            results['changed'] = False
    except:
        module.fail_json(
            msg="Failed to save configuration in {0]".format(host))

    module.exit_json(**results)

from ansible.module_utils.basic import *
main()
